import { Inter } from 'next/font/google';
import 'normalize.css';
import './globals.scss';
import '../scss/app.scss';
import config from '../../config.json';
const inter = Inter({ subsets: ['latin'] });
const { name, altName } = config;
export const metadata = {
	title: `${name} ${altName}`,
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='es'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
